export const SITE_URL = 'https://www.cartise.pt';
export const routes = {
  home: { pt: '/', en: '/en/', title: ['Publicidade TVDE e In-Car DOOH em Portugal', 'In-Car Advertising & DOOH in Portugal'], description: ['Conheça a publicidade digital dentro de veículos TVDE. Explore formatos, consulte cobertura e planeie uma campanha com a Cartise.', 'Explore digital advertising inside ride-hailing vehicles in Portugal. See formats, enquire about coverage and plan a campaign with Cartise.'] },
  solution: { pt: '/publicidade-tvde/', en: '/en/in-car-advertising/', title: ['Publicidade digital em veículos TVDE', 'Digital advertising in ride-hailing vehicles'], description: ['Como funciona o In-Car DOOH da Cartise: ecrãs dentro dos veículos, planeamento da campanha, contexto e acompanhamento para marcas e agências.', 'How Cartise In-Car DOOH works: screens inside vehicles, campaign planning, context and support for brands and agencies.'] },
  formats: { pt: '/formatos/', en: '/en/formats/', title: ['Formatos de publicidade TVDE', 'In-car advertising formats'], description: ['Explore anúncios de exemplo e experimente a sua imagem ou vídeo no tablet Cartise e saiba que materiais preparar para pedir uma proposta de campanha.', 'Explore sample ads and try your own image or video on the Cartise tablet and learn what creative materials to prepare for a campaign proposal.'] },
  coverage: { pt: '/cobertura/', en: '/en/coverage/', title: ['Cobertura de publicidade TVDE em Portugal', 'In-car advertising coverage in Portugal'], description: ['Consulte disponibilidade para Lisboa, Porto, Algarve e outras regiões. Confirme rede, datas e critérios de distribuição antes de reservar.', 'Enquire about Lisbon, Porto, Algarve and other regions. Confirm network availability, dates and distribution criteria before booking.'] },
  fleets: { pt: '/frotas-tvde/', en: '/en/fleets/', title: ['Parcerias com frotas e motoristas TVDE', 'Fleet and driver partnerships'], description: ['Apresente a sua frota à Cartise. Consulte elegibilidade, instalação, manutenção, remuneração e condições de participação na rede.', 'Introduce your fleet to Cartise. Enquire about eligibility, installation, maintenance, remuneration and network participation.'] },
  contact: { pt: '/contacto/', en: '/en/contact/', title: ['Pedir proposta de campanha', 'Request a campaign proposal'], description: ['Conte-nos a cidade, objetivo e período da sua campanha. Fale com a Cartise sobre publicidade digital em veículos TVDE.', 'Tell us your campaign city, objective and dates. Talk to Cartise about digital advertising inside ride-hailing vehicles.'] },
  privacy: { pt: '/privacidade/', en: '/en/privacy/', title: ['Privacidade e contactos', 'Privacy and contact information'], description: ['Saiba como funciona o formulário de contacto, o serviço de envio e a pré-visualização local de ficheiros no estúdio Cartise.', 'Learn how the contact form, delivery service and local file previews in the Cartise studio work.'] },
  tablet: { pt: '/tablet', en: '/en/tablet', title: ['Estúdio de campanha no tablet', 'Tablet campaign studio'], description: ['Experimente a sua imagem ou vídeo no tablet Cartise. Demonstração interativa com exemplos fictícios e ficheiros locais.', 'Try your image or video on the Cartise tablet. An interactive demo with fictional examples and local files.'], noindex: true },
  notFound: { pt: '/404.html', en: '/en/404.html', title: ['Página não encontrada', 'Page not found'], description: ['Encontre a solução, formatos, cobertura e contactos da Cartise.', 'Find the Cartise solution, formats, coverage and contact details.'], noindex: true },
};
export function routeFor(pathname = '/') {
  const lang = pathname === '/en' || pathname.startsWith('/en/') ? 'en' : 'pt';
  const normalized = pathname.replace(/\/index\.html$/, '/').replace(/\/+$/, '') || '/';
  const key = Object.keys(routes).find(key => (routes[key][lang].replace(/\/+$/, '') || '/') === normalized) || 'notFound';
  return { key, lang, path: routes[key][lang], ...routes[key] };
}
export function pageLink(key, lang = 'pt') { return routes[key][lang]; }
